# Netlify 배포 설정
[build]
  publish = "."

# Inblog 서브디렉토리 연동
[[redirects]]
  from = "/blog"
  to = "https://proxy.inblog.dev/bdbddc"
  status = 200
  force = true

[[redirects]]
  from = "/blog/*"
  to = "https://proxy.inblog.dev/bdbddc/:splat"
  status = 200
  force = true
